---
# tasks file for mod-xilinxsrv
- name: Reboot
  become: 'yes'
  ansible.builtin.reboot:

## in case NetworkManager is not used, provide dhclient and bring up manually
#- name: DHCP client for wlan0
#  become: 'yes'
#  shell: |
#    killall dhclient
#    dhclient wlan0

- name: Apt update
  become: 'yes'
  ansible.builtin.apt:
    upgrade: 'yes'
    update_cache: 'yes'
    cache_valid_time: 86400

- name: Install packages
  become: 'yes'
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
    cache_valid_time: 86400

- name: Check /x86 exists
  stat:
    path: /x86
  register: x86_exists

- name: Setup chroot for qemu
  block:

    - name: Create folder /x86
      ansible.builtin.file:
        path: /x86
        state: directory

    - name: Execute debootstrap on /x86
      command:
        cmd: debootstrap --arch amd64 trixie /x86 http://deb.debian.org/debian

    - name: Copy qemu-x86_64-static over to /x86/usr/bin
      ansible.builtin.copy:
#        src: /usr/bin/qemu-x86_64-static
        src: /usr/bin/qemu-x86_64
        dest: /x86/usr/bin/qemu-x86_64-static
        remote_src: yes
        mode: '0755'

    - name: Chroot package update
      shell: |
        chroot /x86 qemu-x86_64-static /bin/bash -c "apt update"

    - name: Chroot package install
      shell: |
        chroot /x86 qemu-x86_64-static /bin/bash -c "apt install -y ncurses-dev libncurses5-dev libncursesw5-dev libx11-6 libxext6 libxtst6 libgtk2.0-0 libglib2.0-0 libstdc++6 libusb-0.1-4 libusb-1.0-0 libftdi1"

    - name: Create folder /x86/xilinx
      ansible.builtin.file:
        path: /x86/xilinx
        state: directory

    - name: Turn off ser2net
      ansible.builtin.copy:
        src: ser2net.yaml
        dest: /etc/ser2net.yaml
 
  when: x86_exists.stat.exists == False
  become: 'yes'

## Note: this setup only installs the qemu / binfmt setup to prepare the
## hw-server installation. Typically hw-server is highly dependend on the Xilinx
## Vivado version. Installation of a particular version is best carried out
## by a .deb package which wraps the x86 hw-server binary into a package to be
## installed into the qemu setup on the RPi.

- name: All done!
  debug:
    msg: Vivado Lab Edition / hw_server installed
