---
# tasks file for rpi
- name: Fix login
  ansible.builtin.command: raspi-config nonint do_boot_behaviour B2

- name: Fix /usr/local permissions
  ansible.builtin.file:
    path: /usr/local
    state: directory
    recurse: yes
    owner: pi
    group: pi

- name: Expand rootfs
  ansible.builtin.command: raspi-config --expand-rootfs

- name: Copy pi configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    group: pi
    mode: 0644
  with_items:
    - { src: home/pi/bashrc, dest: /home/pi/.bashrc }
    - { src: home/pi/vimrc, dest: /home/pi/.vimrc }
    - { src: home/pi/emacsrc, dest: /home/pi/.emacs }
    - { src: home/pi/emacsstarter.sh, dest: /home/pi/.emacsstarter.sh }

- name: Copy mc configs
  copy:
    src: home/pi/config/
    dest: "{{ ansible_env.HOME }}/.config"
    owner: pi
    group: pi

- name: Symlink .local to /usr/local
  file:
    src: /usr/local
    dest: "{{ ansible_env.HOME }}/.local"
    owner: pi
    group: pi
    state: link

- name: Copy etc configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: etc/apt, dest: /etc/apt }
    - { src: etc/default, dest: /etc/default }
    - { src: etc/motion, dest: /etc/motion }
    - { src: etc/group, dest: /etc/group }
    - { src: etc/locale.gen, dest: /etc/locale.gen }
    - { src: etc/screenrc, dest: /etc/screenrc }

- name: Reboot
  ansible.builtin.reboot:

- name: Wifi
  shell: |
    sudo rfkill unblock all
    sudo ifup --force wlan0
  register: os_info
  debugger: on_failed

- name: locales
  block:
    - name: Install locales
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name: locales

    - name: Install elpa-magit
      ansible.builtin.apt:
        name: elpa-magit

    - name: Fix locales
      shell: sudo locale-gen en_US.UTF-8
      register: os_info
      debugger: on_failed

- name: Install package list
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: latest

- name: Reboot
  ansible.builtin.reboot:

- name: Install emacs goodies
  ansible.builtin.apt:
    name: emacs-goodies-el

- name: Reboot
  ansible.builtin.reboot:

- name: Autoclean package list
  ansible.builtin.apt:
    autoclean: yes

- name: Autoremove dependencies no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Enable systemd services
  systemd:
    name: ssh.service
    enabled: true
    masked: no

- name: Reboot
  ansible.builtin.reboot:

- name: All done!
  debug:
    msg: Packages have been successfully installed
