---
# vars file for rpi
user:
  - name: "pi"
    password: "xdr5XDR%"

config_system_locale: 'en_US.UTF-8'
config_system_language: 'en_US.UTF-8'

ansible_python_interpreter: '/usr/bin/python3'

packages:
  - vim
  - vim-addon-manager
  - vim-youcompleteme
  - emacs
  - wget
  - htop
  - tig
  - zlib1g-dev
  - g++
  - build-essential
  - sudo
  - libssl-dev
  - bison
  - flex
  - bc
  - libncurses5-dev
  - libelf-dev
  - python3-all
  - python3-dev
  - rsync
  - binutils
  - unzip
  - bzip2
  - make
  - gcc
  - cpio
  - libc6-dev
  - fakeroot
  - udev
  - hdparm
  - xmlto
  - perl
  - wget
  - curl
  - bin86
  - patch
  - doxygen
  - mercurial
  - kmod
  - fonts-noto-cjk
  - autoconf
  - libtool
  - libtool-bin
  - aptitude
  - bsdmainutils
  - i2c-tools
  - device-tree-compiler
  - graphviz
  - u-boot-tools
  - codespell
  - clang-format
  - clang-tools
  - clang-tidy
  - astyle
  - exuberant-ctags
  - tree
  - mc
  - colordiff
  - dos2unix
  - chrpath
  - diffstat
  - gawk
  - texinfo
  - libsdl1.2-dev
  - xterm
  - screen
  - emacs-goodies-el
  - exuberant-ctags
  - git-core
  - python3
  - python3-virtualenv
  - python3-pip
  - python3-setuptools
  - virtualenv
  - vim-bitbake
  - mosh
  - tcpdump
  - nmap
  - tio
  - xxd
  - lighttpd
  - tftp
  - tftpd-hpa
  - dnsmasq
  - cmake
  - libftdi1-dev
  - zstd
