---
# tasks file for docker
- name: Reboot
  become: 'yes'
  ansible.builtin.reboot:

## in case NetworkManager is not used, provide dhclient and bring up manually
#- name: DHCP client for wlan0
#  become: 'yes'
#  shell: |
#    killall dhclient
#    dhclient wlan0

- name: Install docker
  become: 'yes'
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
    cache_valid_time: 86400

- name: Add the user to group docker
  become: 'yes'
  ansible.builtin.user:
    name: pi
    groups: docker
    append: 'yes'

- name: All done!
  debug:
    msg: Docker installed
