---
# tasks file for rpi
- name: Fix login
  become: 'yes'
  ansible.builtin.command: raspi-config nonint do_boot_behaviour B2

- name: Fix /usr/local permissions
  become: 'yes'
  ansible.builtin.file:
    path: /usr/local
    state: directory
    recurse: yes
    owner: pi
    group: pi

- name: Expand rootfs
  become: 'yes'
  ansible.builtin.command: raspi-config --expand-rootfs

- name: Copy pi configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    group: pi
    mode: 0644
  with_items:
    - { src: home/pi/bashrc, dest: /home/pi/.bashrc }
    - { src: home/pi/vimrc, dest: /home/pi/.vimrc }
    - { src: home/pi/emacsrc, dest: /home/pi/.emacs }
    - { src: home/pi/emacsstarter.sh, dest: /home/pi/.emacsstarter.sh }
    - { src: home/pi/config/, dest: /home/pi/.config }

## actually, for python prefer virtualenv to force linking .local (dirty hack)
- name: Symlink .local to /usr/local
  file:
    src: /usr/local
    dest: "{{ ansible_env.HOME }}/.local"
    owner: pi
    group: pi
    state: link

- name: Copy etc configs
  become: 'yes'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: etc/apt, dest: /etc/apt }
    - { src: etc/motion, dest: /etc/motion }
    - { src: etc/screenrc, dest: /etc/screenrc }
    - { src: etc/sudoers, dest: /etc/sudoers }
    - { src: usr/share/polkit-1, dest: /usr/share/polkit-1 }

- name: Reboot
  become: 'yes'
  ansible.builtin.reboot:

- name: Wifi
  become: 'yes'
  shell: |
    sudo rfkill unblock all
    sudo ifup --force wlan0
  register: os_info
  debugger: on_failed

- name: locales
  become: 'yes'
  block:
    - name: Install locales
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name: locales

    - name: Ensure localisation files for '{{ config_system_locale }}' are available
      locale_gen:
        name: "{{ config_system_locale }}"
        state: present

    - name: Ensure localisation files for '{{ config_system_language }}' are available
      locale_gen:
        name: "{{ config_system_language }}"
        state: present

    - name: Get current locale and language configuration
      command: localectl status
      register: locale_status
      changed_when: false

    - name: Parse 'LANG' from current locale and language configuration
      set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

    - name: Parse 'LANGUAGE' from current locale and language configuration
      set_fact:
        locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

    - name: Configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
      command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
      changed_when: locale_lang != config_system_locale or locale_language != config_system_language

    - name: Reboot
      ansible.builtin.reboot:

## hack: elpa-magit does not install well with others
- name: Install elpa-magit
  become: 'yes'
  ansible.builtin.apt:
    name: elpa-magit

- name: Install package list
  become: 'yes'
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: latest

- name: Reboot
  become: 'yes'
  ansible.builtin.reboot:

## hack: elpa-magit does not install well with other packages...
- name: Install emacs goodies
  become: 'yes'
  ansible.builtin.apt:
    name: emacs-goodies-el

- name: Reboot
  become: 'yes'
  ansible.builtin.reboot:

- name: Enable ssh
  become: 'yes'
  systemd:
    name: ssh.service
    enabled: true
    masked: no

- name: Disable systemd ModemManager
  become: 'yes'
  ansible.builtin.systemd:
    name: ModemManager.service
    enabled: false

- name: Disable systemd apache2
  become: 'yes'
  ansible.builtin.systemd:
    name: apache2.service
    enabled: false

- name: Enable systemd lighttpd
  become: 'yes'
  ansible.builtin.systemd:
    name: lighttpd.service
    enabled: true

- name: Remove apache2
  become: 'yes'
  ansible.builtin.apt:
    name: apache2
    purge: yes

- name: Autoclean package list
  become: 'yes'
  ansible.builtin.apt:
    autoclean: yes

- name: Autoremove dependencies no longer required
  become: 'yes'
  ansible.builtin.apt:
    autoremove: yes

- name: Reboot
  become: 'yes'
  ansible.builtin.reboot:

- name: All done!
  debug:
    msg: Packages have been successfully installed
