---
# tasks file for labgrid provisioning as labgrid-exporter
- name: Reboot
  become: 'yes'
  ansible.builtin.reboot:

## in case NetworkManager is not used, provide dhclient and bring up manually
#- name: DHCP client for wlan0
#  become: 'yes'
#  shell: |
#    killall dhclient
#    dhclient wlan0

## check for conditionals

- name: Check virtualenv exists
  stat:
    path: /opt/labgrid-venv
  register: pip_virtualenv_installed

- name: Check systemd service exists
  stat:
    path: /home/pi/README_labgrid.md
  register: labgrid_exporter_exists

- name: Check gpio26 systemd service exists
  stat:
    path: /etc/systemd/system/gpio26.service
  register: gpio26_service_exists

## install system and packages

- name: Update and upgrade apt packages
  become: 'yes'
  ansible.builtin.apt:
    upgrade: 'yes'
    update_cache: 'yes'

- name: Install packages
  become: 'yes'
  ansible.builtin.apt:
    pkg: "{{ item }}"
  with_items:
    - python3
    - python3-virtualenv
    - python3-pip
    - python3-setuptools
    - virtualenv
    - ser2net
    - microcom

- name: Change permission for /opt
  become: 'yes'
  ansible.builtin.file:
    dest: "/opt"
    owner: pi
    group: pi
    recurse: 'yes'

- name: Create virtualenv
  command:
    cmd: virtualenv /opt/labgrid-venv -p python3
    creates: "labgrid-venv"
  when: pip_virtualenv_installed.stat.exists == False

## pyserial: this version should be used (10/2022)
- name: Fix pyserial reinstall
  pip:
    name: https://github.com/labgrid-project/pyserial/archive/v3.4.0.1.zip#egg=pyserial
    state: forcereinstall
    virtualenv: /opt/labgrid-venv

- name: Install python packages
  become: 'yes'
  pip:
    name:
      - setuptools
      - wheel
    virtualenv: /opt/labgrid-venv

- name: Clone, install labgrid and install requirements
  pip:
    name: git+https://github.com/labgrid-project/labgrid
    virtualenv: /opt/labgrid-venv

## add user pi to groups
- name: Add user to several groups
  become: 'yes'
  ansible.builtin.user:
    name: pi
    groups: dialout,plugdev,spi,i2c,gpio,disk 
    append: 'yes'

## systemd gpio26 for power cycling

- name: GPIO26 for DUT power control
  block:
    - name: Prepare GPIO26 script
      copy:
        src: _gpio.sh
        dest: /usr/bin/_gpio.sh
        mode: 755

    - name: Link to GPIO26
      ansible.builtin.file:
        src: /usr/bin/_gpio.sh
        dest: /usr/bin/gpio26.sh
        state: link

    - name: Add GPIO26 systemd service script
      copy:
        src: gpio26.service
        dest: "{{ gpio26_service_path }}"
        owner: root
        group: root

    - name: Reload systemd services
      systemd:
        daemon_reload: 'yes'
  when: gpio26_service_exists.stat.exists == False
  become: 'yes'

## Labgrid Exporter Setup

- name: Setup systemd
  block:
    - name: Copy /etc/tmpfiles.d files
      ansible.builtin.copy:
        src: systemd/tmpfiles.d/labgrid.conf
        dest: /etc/tmpfiles.d

    - name: Copy /usr/lib/sysusers.d files
      ansible.builtin.copy:
        src: systemd/sysusers.d/labgrid.conf
        dest: /usr/lib/sysusers.d

    - name: Copy systemd service
      ansible.builtin.copy:
        src: systemd/labgrid-exporter.service
        dest: /etc/systemd/system

    - name: Copy labgrid-exporter config file
      ansible.builtin.copy:
        src: exporter
        dest: /etc/labgrid

    - name: Link to active labgrid-exporter config file
      ansible.builtin.file:
        src: /etc/labgrid/exporter/config_mini.yml
        dest: /etc/labgrid/exporter.yaml
        state: link

    - name: Reload systemd services
      systemd:
        daemon_reload: 'yes'

    - name: Add Labgrid-Exporter README
      copy:
        src: README_labgrid.md
        dest: /home/pi/
        owner: pi
        group: pi
        mode: '0644'

  when: labgrid_exporter_exists.stat.exists == False
  become: 'yes'

## message of the day / greeter
- name: Setup some message
  become: 'yes'
  copy:
    src: motd
    dest: /etc/motd
    mode: 0644

- name: All done!
  debug:
    msg: Labgrid installed
