- name: Raspberry Provisioning
  hosts: raspi
  become: 'no'
  tasks:
    - name: Common RPI
      import_role:
        name: common-rpi64

    - name: Labgrid
      import_role:
        name: labgrid

    - name: USB-SD Mux
      import_role:
        name: usbsdmux

    - name: Docker setup
      import_role:
        name: docker

    - name: X11 setup
      import_role:
        name: x11

## NB: not needed for driving (single) relays by gpio
#    - name: Relay Control
#      import_role:
#        name: relayctl

#    - name: Xilinx Virtual Cable
#      import_role:
#        name: xvcpi
