- name: Raspberry Provisioning
  hosts: raspi
  become: 'no'
  tasks:
    - name: Common RPI
      import_role:
        name: rpi

    - name: Labgrid
      import_role:
        name: labgrid

    - name: Relay Control
      import_role:
        name: relayctl

    - name: Xilinx Virtual Cable
      import_role:
        name: xvcpi


