---
- name: Raspberry Provisioning
  hosts: all
  become: 'yes'
  vars:
    user:
      - name: "pi"
        password: "xdr5XDR%"
    packages:
      - vim
      - emacs
      - wget
      - htop
      - tig
      - zlib1g-dev
      - g++
      - build-essential
      - sudo
      - libssl-dev
      - bison
      - flex
      - bc
      - libncurses5-dev
      - libelf-dev
      - python3-all
      - rsync
      - binutils
      - unzip
      - bzip2
      - make
      - gcc
      - cpio
      - libc6-dev
      - fakeroot
      - udev
      - hdparm
      - xmlto
      - perl
      - wget
      - curl
      - bin86
      - patch
      - doxygen
      - python-is-python2
      - mercurial
      - kmod
      - fonts-noto-cjk
      - autoconf
      - libtool
      - libtool-bin
      - aptitude
      - bsdmainutils
      - i2c-tools
      - device-tree-compiler
      - graphviz
      - u-boot-tools
      - codespell
      - clang-format
      - clang-tools
      - clang-tidy
      - astyle
      - exuberant-ctags
      - tree
      - mc
      - colordiff
      - dos2unix
      - chrpath
      - diffstat
      - gawk
      - texinfo
      - libsdl1.2-dev
      - xterm
      - screen
      - emacs-goodies-el
      - exuberant-ctags
      - git-all
      - python3
      - python3-virtualenv
      - python3-pip
      - python3-setuptools
      - virtualenv
      - vim-bitbake
  tasks:
    - name: Fix login
      ansible.builtin.command: raspi-config nonint do_boot_behaviour B2
    - name: Fix /usr/local permissions
      ansible.builtin.command: chown pi:pi -R /usr/local
    - name: Expand rootfs
      ansible.builtin.command: raspi-config --expand-rootfs
    - name: Reboot
      ansible.builtin.command: reboot
      ignore_unreachable: yes
    - name: Wait
      wait_for_connection:
        delay: 30
    - name: Wifi
      shell: |
        sudo rfkill unblock all
        sudo ip link set wlan0 up
        sudo dhclient -v wlan0
        sudo iw wlan0 set power_save off
        sudo wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
        sudo ifup --force wlan0
      register: os_info
      debugger: on_failed
    - name: locales
      block:
        - name: Install locales
          apt:
            update_cache: yes
            name: locales
            state: latest
        - name: Fix locales
          shell: sudo locale-gen en_US.UTF-8
          register: os_info
          debugger: on_failed
    - name: Install package list
      register: updatesys
      apt:
        update_cache: yes
        name: "{{ packages }}"
        state: latest
        autoclean: yes
      debugger: on_failed
#    - name: Install Labgrid
#      shell: |
#        pip install --upgrade pip setuptools wheel
#        git clone https://github.com/labgrid-project/labgrid
#        cd labgrid && pip install -r requirements.txt
#        python3 setup.py install
#      register: os_info
    - name: Enable systemd services
      systemd:
        name: ssh.service
        enabled: true
        masked: no
    - name: All done!
      debug:
        msg: Packages have been successfully installed
